require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'pdfbook' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'

  pod 'react-native-progress-view', :path => '../node_modules/@react-native-community/progress-view'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'



  permissions_path = '../node_modules/react-native-permissions/ios'

 
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders.podspec"



  target 'pdfbookTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'pdfbook-tvOS' do
  # Pods for pdfbook-tvOS

  target 'pdfbook-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
